filebeat.inputs:
   - type: log
     enabled: true
     paths:
        - '/var/log/postgresql/*.log'
        
filebeat.modules:
    - module: postgresql
      log:
        enabled: true
        paths:
            - '/var/log/postgresql/*.log'
            # var.paths: ["/path/to/log/postgres/*.log*"]

output.logstash:
   enabled: true
   hosts: ["logstash:5044"]
